11/17/2014 23:14:47 WARNING nemoa.system.classes.base.get -> unknown key 'algoruthms'
12/02/2014 22:23:48 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:35:31 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:41:49 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:48:13 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:50:55 WARNING nemoa.workspace.base.get -> could not get configuration: model with name 'multiplacation' is not known.
12/02/2014 22:50:55 ERROR nemoa.model.imports.load -> could not import model: current workspace 'tutorial' does not contain a model 'multiplacation'.
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main->   "__main__", fname, loader, pkg_name)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\runpy.py", line 72, in _run_code->   exec code in run_globals
12/02/2014 22:50:55 ERROR File "c:\Python27\scripts\ipython.exe\__main__.py", line 9, in <module>->   sys.exit(start_ipython())
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\config\application.py", line 564, in launch_instance->   app.start()
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\terminal\ipapp.py", line 371, in start->   self.shell.mainloop()
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2827, in run_ast_nodes->   if self.run_code(code):
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/02/2014 22:50:55 ERROR File "<ipython-input-6-c7a8196f6c49>", line 1, in <module>->   model = nemoa.model.open('multiplacation')
12/02/2014 22:50:55 ERROR File "./package\nemoa\model\__init__.py", line 34, in open->   return new(**load(*args, **kwargs))
12/02/2014 22:50:55 ERROR File "./package\nemoa\model\__init__.py", line 26, in load->   return nemoa.model.imports.load(*args, **kwargs)
12/02/2014 22:50:55 ERROR File "./package\nemoa\model\imports\__init__.py", line 57, in load->   '%s'.""" % (current_workspace, path))
12/02/2014 22:50:55 ERROR File "./package\nemoa\common\log.py", line 174, in log->   for line in traceback.format_stack():
12/02/2014 23:26:31 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:30:40 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:31:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:32:28 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:33:12 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:36:56 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/04/2014 22:29:37 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/04/2014 22:47:53 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/04/2014 22:49:08 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 17:06:14 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 17:06:32 WARNING nemoa.system.classes.base.get -> unknown key 'error'
12/05/2014 17:06:47 WARNING nemoa.model.classes.base.calc -> could not evaluate model
12/05/2014 17:07:15 WARNING nemoa.model.classes.base.calc -> could not evaluate model
12/05/2014 18:18:33 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:19:06 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:22:24 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:35:11 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:37:55 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:27:10 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:28:09 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:32:36 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:35:39 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:37:14 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:40:43 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:41:38 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:42:00 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:47:24 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:50:45 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:56:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 13:59:40 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:04:28 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:05:26 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:10:49 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:13:48 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:15:42 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:36:21 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:37:50 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 14:39:48 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 15:03:38 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 15:05:32 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 15:15:45 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 15:19:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 15:37:29 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 15:37:32 ERROR nemoa.system.classes.base._eval_system -> could not evaluate system: unknown algorithm name 'precision'.
12/06/2014 15:37:32 ERROR File "/usr/bin/ipython", line 5, in <module>->   start_ipython()
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 565, in launch_instance->   app.start()
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 371, in start->   self.shell.mainloop()
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes->   if self.run_code(code):
12/06/2014 15:37:32 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/06/2014 15:37:32 ERROR File "<ipython-input-2-8b674c783273>", line 1, in <module>->   model.precision
12/06/2014 15:37:32 ERROR File "./package/nemoa/model/classes/base.py", line 87, in __getattr__->   if 'r' in self._attr[key]: return self.get(key)
12/06/2014 15:37:32 ERROR File "./package/nemoa/model/classes/base.py", line 201, in get->   if key == 'precision': return self.evaluate('system', 'precision')
12/06/2014 15:37:32 ERROR File "./package/nemoa/model/classes/base.py", line 555, in evaluate->   return self.system.evaluate(data, *args, **kwargs)
12/06/2014 15:37:32 ERROR File "./package/nemoa/system/classes/base.py", line 988, in evaluate->   return self._eval_system(data, *args, **kwargs)
12/06/2014 15:37:32 ERROR File "./package/nemoa/system/classes/base.py", line 1016, in _eval_system->   unknown algorithm name '%s'.""" % (func))
12/06/2014 15:37:32 ERROR File "./package/nemoa/common/log.py", line 174, in log->   for line in traceback.format_stack():
12/06/2014 15:37:40 ERROR nemoa.system.classes.base._eval_system -> could not evaluate system: unknown algorithm name 'error'.
12/06/2014 15:37:40 ERROR File "/usr/bin/ipython", line 5, in <module>->   start_ipython()
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 565, in launch_instance->   app.start()
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 371, in start->   self.shell.mainloop()
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes->   if self.run_code(code):
12/06/2014 15:37:40 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/06/2014 15:37:40 ERROR File "<ipython-input-3-2e9825eb9937>", line 1, in <module>->   model.error
12/06/2014 15:37:40 ERROR File "./package/nemoa/model/classes/base.py", line 87, in __getattr__->   if 'r' in self._attr[key]: return self.get(key)
12/06/2014 15:37:40 ERROR File "./package/nemoa/model/classes/base.py", line 199, in get->   if key == 'error': return self.evaluate('system', 'error')
12/06/2014 15:37:40 ERROR File "./package/nemoa/model/classes/base.py", line 555, in evaluate->   return self.system.evaluate(data, *args, **kwargs)
12/06/2014 15:37:40 ERROR File "./package/nemoa/system/classes/base.py", line 988, in evaluate->   return self._eval_system(data, *args, **kwargs)
12/06/2014 15:37:40 ERROR File "./package/nemoa/system/classes/base.py", line 1016, in _eval_system->   unknown algorithm name '%s'.""" % (func))
12/06/2014 15:37:40 ERROR File "./package/nemoa/common/log.py", line 174, in log->   for line in traceback.format_stack():
12/06/2014 16:13:20 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 16:13:40 WARNING nemoa.system.classes.base.evaluate -> unsupported system evaluation 'relation'
12/06/2014 16:13:50 WARNING nemoa.system.classes.base.evaluate -> unsupported system evaluation 'relation'
12/06/2014 16:15:46 ERROR nemoa.system.classes.base._eval_relation -> could not evaluate system unit relation: unknown algorithm name 'variance'.
12/06/2014 16:15:46 ERROR File "/usr/bin/ipython", line 5, in <module>->   start_ipython()
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 565, in launch_instance->   app.start()
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 371, in start->   self.shell.mainloop()
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes->   if self.run_code(code):
12/06/2014 16:15:46 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/06/2014 16:15:46 ERROR File "<ipython-input-14-9e9de4874b62>", line 1, in <module>->   model.evaluate('system', 'relations', 'variance')
12/06/2014 16:15:46 ERROR File "./package/nemoa/model/classes/base.py", line 555, in evaluate->   return self.system.evaluate(data, *args, **kwargs)
12/06/2014 16:15:46 ERROR File "./package/nemoa/system/classes/base.py", line 982, in evaluate->   return self._eval_relation(data, *args[1:], **kwargs)
12/06/2014 16:15:46 ERROR File "./package/nemoa/system/classes/base.py", line 1193, in _eval_relation->   unknown algorithm name '%s'.""" % (func))
12/06/2014 16:15:46 ERROR File "./package/nemoa/common/log.py", line 174, in log->   for line in traceback.format_stack():
12/06/2014 16:19:10 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 16:20:18 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 16:20:48 ERROR nemoa.system.classes.base._eval_links -> could not evaluate system links: unknown algorithm name 'energy'.
12/06/2014 16:20:48 ERROR File "/usr/bin/ipython", line 5, in <module>->   start_ipython()
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/config/application.py", line 565, in launch_instance->   app.start()
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/ipapp.py", line 371, in start->   self.shell.mainloop()
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/terminal/interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2833, in run_ast_nodes->   if self.run_code(code):
12/06/2014 16:20:48 ERROR File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/06/2014 16:20:48 ERROR File "<ipython-input-3-1fec9d3a8e65>", line 1, in <module>->   model.evaluate('system', 'links', 'energy')
12/06/2014 16:20:48 ERROR File "./package/nemoa/model/classes/base.py", line 555, in evaluate->   return self.system.evaluate(data, *args, **kwargs)
12/06/2014 16:20:48 ERROR File "./package/nemoa/system/classes/base.py", line 978, in evaluate->   return self._eval_links(data, *args[1:], **kwargs)
12/06/2014 16:20:48 ERROR File "./package/nemoa/system/classes/base.py", line 1118, in _eval_links->   unknown algorithm name '%s'.""" % (func))
12/06/2014 16:20:48 ERROR File "./package/nemoa/common/log.py", line 174, in log->   for line in traceback.format_stack():
12/06/2014 16:21:44 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 16:36:56 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 16:37:48 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:19:03 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:23:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:25:48 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:28:47 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:30:52 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:34:06 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:41:36 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:45:23 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:47:32 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:48:58 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:49:30 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:50:38 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 17:52:33 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 18:11:13 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 18:17:49 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/06/2014 18:34:38 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/07/2014 13:12:58 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 13:28:39 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 13:32:26 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 13:32:53 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 13:41:29 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 13:43:01 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 13:48:19 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 15:55:27 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 16:39:38 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 16:41:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 16:43:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/08/2014 17:21:45 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:38:40 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:40:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:46:55 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:48:20 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:57:09 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:57:50 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 11:59:51 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 12:16:16 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:21:25 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:22:09 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:25:25 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:31:46 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:32:52 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:36:47 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:38:26 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:39:35 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:41:35 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:44:29 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:51:42 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:53:36 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 13:57:29 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 14:13:21 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 14:21:05 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 14:23:25 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 14:28:10 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 14:33:38 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/09/2014 14:35:25 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 13:47:06 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 13:51:45 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:00:00 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:13:11 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:21:04 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:23:15 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:38:02 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:39:15 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:41:18 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 14:43:15 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/10/2014 15:17:32 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
