11/17/2014 23:14:47 WARNING nemoa.system.classes.base.get -> unknown key 'algoruthms'
12/02/2014 22:23:48 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:35:31 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:41:49 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:48:13 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 22:50:55 WARNING nemoa.workspace.base.get -> could not get configuration: model with name 'multiplacation' is not known.
12/02/2014 22:50:55 ERROR nemoa.model.imports.load -> could not import model: current workspace 'tutorial' does not contain a model 'multiplacation'.
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main->   "__main__", fname, loader, pkg_name)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\runpy.py", line 72, in _run_code->   exec code in run_globals
12/02/2014 22:50:55 ERROR File "c:\Python27\scripts\ipython.exe\__main__.py", line 9, in <module>->   sys.exit(start_ipython())
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\__init__.py", line 120, in start_ipython->   return launch_new_instance(argv=argv, **kwargs)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\config\application.py", line 564, in launch_instance->   app.start()
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\terminal\ipapp.py", line 371, in start->   self.shell.mainloop()
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 443, in mainloop->   self.interact(display_banner=display_banner)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\terminal\interactiveshell.py", line 567, in interact->   self.run_cell(source_raw, store_history=True)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2741, in run_cell->   interactivity=interactivity, compiler=compiler)
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2827, in run_ast_nodes->   if self.run_code(code):
12/02/2014 22:50:55 ERROR File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2883, in run_code->   exec(code_obj, self.user_global_ns, self.user_ns)
12/02/2014 22:50:55 ERROR File "<ipython-input-6-c7a8196f6c49>", line 1, in <module>->   model = nemoa.model.open('multiplacation')
12/02/2014 22:50:55 ERROR File "./package\nemoa\model\__init__.py", line 34, in open->   return new(**load(*args, **kwargs))
12/02/2014 22:50:55 ERROR File "./package\nemoa\model\__init__.py", line 26, in load->   return nemoa.model.imports.load(*args, **kwargs)
12/02/2014 22:50:55 ERROR File "./package\nemoa\model\imports\__init__.py", line 57, in load->   '%s'.""" % (current_workspace, path))
12/02/2014 22:50:55 ERROR File "./package\nemoa\common\log.py", line 174, in log->   for line in traceback.format_stack():
12/02/2014 23:26:31 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:30:40 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:31:41 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:32:28 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:33:12 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/02/2014 23:36:56 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/04/2014 22:29:37 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/04/2014 22:47:53 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/04/2014 22:49:08 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 17:06:14 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 17:06:32 WARNING nemoa.system.classes.base.get -> unknown key 'error'
12/05/2014 17:06:47 WARNING nemoa.model.classes.base.calc -> could not evaluate model
12/05/2014 17:07:15 WARNING nemoa.model.classes.base.calc -> could not evaluate model
12/05/2014 18:18:33 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:19:06 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:22:24 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:35:11 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
12/05/2014 18:37:55 WARNING nemoa.workspace.base._set_workspace -> could not open workspace 'unittest': folder could not be found in './user/'.
